### PR TITLE
Add compact logo

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
This provides a nice image for [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) :slightly_smiling_face: The PNG image is used. I have also included the SVG image in case we want to customize it later.

### CODE REVIEW

**Comment by Bee-Mar** [comment]
This is great, I didn't realize you were hosting a page with that kind of information on it !

**Comment by KristjanESPERANTO** [comment]
Nice. Now mmpm looks much nicer in the list :rocket:

> This is great, I didn't realize you were hosting a page with that kind of information on it !

Yeah, somehow I was missing a list like this (with filters and screenshots and stuff). I think we can find some synergies with mmpm. Maybe even merge the two into an app store or something similar in the long term.

I don't have much energy right now to push it in that direction, but I think it would be a good direction.

**Comment by Bee-Mar** [comment]
That would be nice. Before embarking on that, I'd like to get an arrangement with the MagicMirror creator so we're all on the same page as well. Since anyone can edit the 3rd Party Package list things can break randomly, and it could be a fair bit of effort to turn it into an app-store of sorts

**Comment by KristjanESPERANTO** [comment]
Yes, we definitely need a better procedure for the list. I think it would be good if we had a good concrete proposal as to how we would ideally like to do this. But I haven't come up with a great approach yet. We could research how other projects approach this.

**Comment by khassel** [comment]
@KristjanESPERANTO  I agree, the current wiki is horrible.

> We could research how other projects approach this.

good idea.

I was thinking of a repo (e.g. yours) which holds a json or yaml structure for the module list and new modules are onboarded via PR's (merge maybe could be automated if some checks passes). This repo could be moved under MagicMirrorOrg when "ready for production".

**Comment by KristjanESPERANTO** [comment]
I'm open to giving it a shot. Then we would have a more concrete basis for further discussion.

In the next two weeks I will be on the go a lot, but I will try to make a draft. If any of you would like to take it on, I won't be sad :slightly_smiling_face:

**Pull request merged**
